language: python
python:
  - "3.4"
  - "3.5"
#before_install:
# - sudo apt-get install python3-venv
install:
    pip install -r requirements.txt
script: 
  - coverage run --source ccp_daily_automation.py  test.py
after_success:
  - coveralls
